#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE metabase;
    CREATE DATABASE n8n;
    GRANT ALL PRIVILEGES ON DATABASE metabase TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE n8n TO "$POSTGRES_USER";
EOSQL
